from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image
)
from reportlab.lib.units import inch
from datetime import datetime
import os


def create_pdf(
    prediction,
    confidence,
    score,
    ai_report,
    original_image,
    heatmap_image,
    output_path="outputs/Inspection_Report.pdf"
):

    os.makedirs("outputs", exist_ok=True)

    doc = SimpleDocTemplate(output_path)

    styles = getSampleStyleSheet()

    story = []

    # -------------------------
    # Title
    # -------------------------

    story.append(
        Paragraph(
            "<b><font size=20>"
            "Industrial Quality Inspection Report"
            "</font></b>",
            styles["Title"]
        )
    )

    story.append(Spacer(1, 0.25 * inch))

    # -------------------------
    # Date
    # -------------------------

    story.append(
        Paragraph(
            f"<b>Date:</b> {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            "<b>Inspection Type:</b> Automated Visual Inspection",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 0.2 * inch))

    # -------------------------
    # Prediction
    # -------------------------

    story.append(
        Paragraph(
            "<b>Prediction</b>",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(f"Result : {prediction}", styles["Normal"])
    )

    story.append(
        Paragraph(f"Confidence : {confidence:.2f}%", styles["Normal"])
    )

    story.append(
        Paragraph(f"Anomaly Score : {score:.4f}", styles["Normal"])
    )

    story.append(Spacer(1, 0.2 * inch))

    # -------------------------
    # Original Image
    # -------------------------

    if os.path.exists(original_image):

        story.append(
            Paragraph(
                "<b>Original Image</b>",
                styles["Heading2"]
            )
        )

        story.append(Image(original_image, width=4*inch, height=4*inch))

        story.append(Spacer(1, 0.2 * inch))

    # -------------------------
    # Heatmap
    # -------------------------

    if os.path.exists(heatmap_image):

        story.append(
            Paragraph(
                "<b>Heatmap</b>",
                styles["Heading2"]
            )
        )

        story.append(Image(heatmap_image, width=4*inch, height=4*inch))

        story.append(Spacer(1, 0.2 * inch))

    # -------------------------
    # AI Report
    # -------------------------

    story.append(
        Paragraph(
            "<b>AI Inspection Report</b>",
            styles["Heading2"]
        )
    )

    report = ai_report.replace("\n", "<br/>")

    story.append(
        Paragraph(report, styles["BodyText"])
    )

    story.append(Spacer(1, 0.3 * inch))

    story.append(
        Paragraph(
            "<b>Generated By</b><br/>"
            "AI-Powered Industrial Surface Defect Detection System",
            styles["Italic"]
        )
    )

    doc.build(story)

    return output_path